### ISSUE TITLE
Build fails on Android

### ISSUE THREAD

**Issue by hansemannn** [AndreaVitale/av.imageview#58]
Hey there!

Awesome module, thank you @AndreaVitale! We are using this module for iOS and it works fine. For Android, we get a build error about duplicate symbols:
```
[ERROR] Failed to run dexer:
[ERROR]
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/package-info;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Address;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Authenticator;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Authenticator$1;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$1;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$2;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$CacheRequestImpl;
[ERROR] Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$CacheRequestImpl$1;
[ERROR]
[ERROR] UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] java.lang.RuntimeException: Translation has been interrupted
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:615)
[ERROR]         at com.android.dx.command.dexer.Main.runMultiDex(Main.java:368)
[ERROR]         at com.android.dx.command.dexer.Main.runDx(Main.java:289)
[ERROR]         at com.android.dx.command.dexer.Main.main(Main.java:247)
[ERROR]         at com.android.dx.command.Main.main(Main.java:94)
[ERROR] Caused by: java.lang.InterruptedException: Too many errors
[ERROR]         at com.android.dx.command.dexer.Main.processAllFiles(Main.java:607)
[ERROR]         ... 4 more
```
It looks like the `okhttp` library is causing the issue, which is also added by the SDK. Maybe it can be removed? Does someone use this module in 7.4.1.GA+?

**Comment by hansemannn** [comment]
Note: If I remove the okhttp libraries from the module, the build and module work fine. But then the module build itself fails. There could be a hook that removes `okhttp-3.9.0.jar` from `lib/` after compiling.

**Comment by m1ga** [comment]
Interesting. I'm using the module with 7.4.1.GA and tested it with 7.5.0 (a bit older) without a problem. My module list:
```
<module>ti.map</module>
<module platform="android">bencoding.android.tools</module>
<module platform="android">ti.goosh</module>
<module platform="android">ti.playservices</module>
<module platform="ios">dk.napp.slidemenu</module>
<module platform="commonjs">reste</module>
<module>av.imageview</module>
<module>ti.animation</module>
<module platform="android">ti.barcode</module>
<module platform="ios">com.mfogg.squarecamera</module>
```
No `okhttp` clash

**Comment by hansemannn** [comment]
Whoops, it's [`ti.socketio`](https://github.com/appcelerator-modules/titanium-socketio/tree/master/android/lib) having duplicate dependencies. I think if the versions would be aligned, it should solve the issue. Latest is 3.11.0 which could simply be added to both projects in hand with a new version to align each other. As a workaround, I just deleted it for now.

**Comment by albert0m** [comment]
I have the same problem, but I honestly wouldn't know which module I could take out (they're all necessary for the app).

this is the list of modules I'm using:

 av.imageview
com.williamrijksen.onesignal
org.iotashan.TiTouchImageView
ti.barcode
ti.imagefactory
ti.map
ti.playservices

**Comment by m1ga** [comment]
@marconealberto with the okhttp error?

**Comment by albert0m** [comment]
yes, I just downloaded the compiled module and imported it in my project but it fails with the same error:

```
[ERROR]  Failed to run dexer:
[ERROR]  
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/package-info;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Address;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Authenticator;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Authenticator$1;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$1;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$2;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$CacheRequestImpl;
[ERROR]  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lokhttp3/Cache$CacheRequestImpl$1;
```

I tried to recompile it from scratch but it fails:

```
[ERROR] Failed to compile Java source files:
[ERROR]   
[ERROR] Likely fix is to remove from proxy.propertyAccessors listing, as both getter and setter methods are defined.
```

**Comment by m1ga** [comment]
check the modules /lib folders for other okhttp files. The original error was fixed by updating the libraries in av.imageview in version 3.2.1. So it looks like you have a newer/different file somewhere.

And that error occurs, when you try to compile the module with the latest Titanium SDK. You can either adjust the code or use an older SDK to compile the module (it will still work with 7.5.0 after compilation).

**Comment by albert0m** [comment]
great stuff, I removed the okhttp files from the /lib module and it works.
